INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);
INSERT INTO users (name, age) VALUES ("name", 7);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("name", "name", 7, '2013-10-02', '2013-10-30');

INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 1, 2);